# Generated by Django 5.2 on 2025-04-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=100, unique=True)),
                ('placa', models.CharField(max_length=50, unique=True)),
                ('fecha_compra', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fotografia', models.ImageField(upload_to='vehiculos_fotos/')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
