# Generated by Django 5.2 on 2025-04-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('curp', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_licencia', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=100, unique=True)),
                ('placa', models.CharField(max_length=50, unique=True)),
                ('fecha_compra', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fotografia', models.ImageField(upload_to='vehiculos_fotos/')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('codigo_invitacion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chofer')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_recorrido', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('exitosa', models.BooleanField(default=True)),
                ('descripcion_problema', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('latitud_origen', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud_origen', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitud_destino', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud_destino', models.DecimalField(decimal_places=6, max_digits=9)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.chofer')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vehiculo')),
            ],
            options={
                'unique_together': {('vehiculo', 'fecha_recorrido')},
            },
        ),
    ]
