# Generated by Django 5.2 on 2025-04-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField(auto_now_add=True)),
                ('curp', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_licencia', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
