# Generated by Django 5.2 on 2025-04-30 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chofer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chofer')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo')),
            ],
        ),
    ]
