# Generated by Django 5.2 on 2025-04-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chofer_fecha_nacimiento_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_modificacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
