# Generated by Django 5.2 on 2025-04-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_asignacion_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_recorrido', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('exitosa', models.BooleanField(default=True)),
                ('descripcion_problema', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('latitud_origen', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud_origen', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitud_destino', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud_destino', models.DecimalField(decimal_places=6, max_digits=9)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.chofer')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vehiculo')),
            ],
            options={
                'unique_together': {('vehiculo', 'fecha_recorrido')},
            },
        ),
    ]
